export { loadConfig, loadConfigSafe } from './load.js';
export { getConfigPath, getConfigDir } from './paths.js';
export {
  ConfigSchema,
  ConfigSchemaV2,
  LegacyConfigSchemaV1,
  LegacyConfigSchemaV0,
  SelfConfigSchema,
  ContactConfigSchema,
  ContactsConfigSchema,
  NotificationsConfigSchema,
  RuntimeConfigSchema,
  isConfigV2,
  isConfigV1,
  getSelfId,
  getSelfLocalRepoPath,
  getSelfRemoteRepoUrl,
  getContactRemoteRepoUrl,
  getContactNames,
  getContactRepoPath,
  getAgentRepoPath,
  getAgentEntries,
  getHostIntegrationConfig,
  unknownAgentError,
  type Config,
  type ConfigV2,
  type LegacyConfigV1,
  type LegacyConfigV0,
  type SelfConfig,
  type AgentConfig,
  type ContactConfig,
  type ContactsConfig,
  type NotificationsConfig,
  type RuntimeConfig,
  type HappyClawHostConfig,
  type HostIntegrationConfig,
} from './schema.js';
