export { loadConfig, loadConfigSafe } from './load.js';
export { getConfigPath, getConfigDir } from './paths.js';
export {
  ConfigSchema,
  ConfigSchemaV3,
  ProfileSchema,
  ProfileSelfConfigSchema,
  ProfileContactConfigSchema,
  NotificationsConfigSchema,
  RuntimeConfigSchema,
  ActivationConfigSchema,
  FeishuActivatorConfigSchema,
  HappyClawHostConfigSchema,
  HostIntegrationConfigSchema,
  LegacySelfConfigSchema,
  LegacyContactConfigSchema,
  isConfigV3,
  isConfigV2,
  isConfigV1,
  getProfileSelfId,
  getProfileSelfRemoteRepoUrl,
  getProfileContactRemoteRepoUrl,
  getProfileContactNames,
  getProfileHostIntegrationConfig,
  type Config,
  type ConfigV3,
  type ProfileConfig,
  type ProfileSelfConfig,
  type ProfileContactConfig,
  type NotificationsConfig,
  type RuntimeConfig,
  type ActivationConfig,
  type FeishuActivatorConfig,
  type HappyClawHostConfig,
  type HostIntegrationConfig,
  type LegacySelfConfig,
  type LegacyContactConfig,
} from './schema.js';
export {
  resolveProfile,
  requireProfile,
  getProfileNames,
  hasProfile,
} from './profile.js';
